import os
import json
import sqlite3
import httpx
import logging
from datetime import datetime
from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from enum import Enum
from pathlib import Path
from typing import Dict, List, Optional, Tuple

from pulse import __version__
from pulse.config import get_config_dir, get_env_file_path, get_setting
from pulse.history.db import get_db_path

logger = logging.getLogger(__name__)

class CheckStatus(str, Enum):
    PASS = "PASS"
    WARNING = "WARNING"
    FAIL = "FAIL"

@dataclass
class CheckResult:
    name: str
    category: str
    status: CheckStatus
    score_points: int
    max_points: int = 20
    message: str = ""
    details: List[str] = field(default_factory=list)


class DoctorCheck(ABC):
    """Abstract base class for modular system diagnostic checks."""

    @abstractmethod
    def run(self) -> CheckResult:
        pass


class ConfigurationCheck(DoctorCheck):
    def run(self) -> CheckResult:
        from pulse.core.config_service import ConfigService
        cs = ConfigService.get_instance()

        details = []
        points = 20
        status = CheckStatus.PASS

        env_path = get_env_file_path()
        if not env_path.exists():
            details.append("Configuration file '.env' does not exist (using default schema)")
            points -= 5
            status = CheckStatus.WARNING
        else:
            details.append("✓ Configuration file '.env' exists")

        ver = cs.get("CONFIG_SCHEMA_VERSION", 1)
        if ver < 2:
            details.append(f"⚠ Legacy configuration version ({ver}) detected")
            points -= 5
            status = CheckStatus.WARNING
        else:
            details.append(f"✓ Configuration schema version: {ver}")

        gen_by = cs.get("CONFIG_GENERATED_BY", "Unknown")
        details.append(f"✓ Generated by: PULSE {gen_by}")

        diffs = cs.diff_config()
        if diffs:
            details.append(f"✓ Customized settings: {len(diffs)} custom override(s)")

        return CheckResult(
            name="Configuration Check",
            category="Configuration",
            status=status,
            score_points=max(0, points),
            message=f"Configuration schema v{ver} active",
            details=details
        )


class FilesystemCheck(DoctorCheck):
    def run(self) -> CheckResult:
        config_dir = get_config_dir()
        reports_dir = config_dir / "reports"
        cache_dir = config_dir / "cache"

        details = []
        points = 20
        status = CheckStatus.PASS

        if not config_dir.exists():
            details.append(f"✖ Config dir '{config_dir}' missing")
            points -= 10
            status = CheckStatus.FAIL
        else:
            details.append(f"✓ Primary config directory exists: {config_dir}")

        for d_name, d_path in [("Reports", reports_dir), ("Cache", cache_dir)]:
            try:
                d_path.mkdir(parents=True, exist_ok=True)
                test_file = d_path / ".perm_check.tmp"
                with open(test_file, "w") as f:
                    f.write("test")
                test_file.unlink()
                details.append(f"✓ {d_name} directory writable: {d_path}")
            except Exception as e:
                details.append(f"✖ {d_name} directory write failure: {e}")
                points -= 10
                status = CheckStatus.FAIL

        return CheckResult(
            name="Filesystem Check",
            category="Filesystem",
            status=status,
            score_points=max(0, points),
            message="Storage directories validated",
            details=details
        )


class DatabaseCheck(DoctorCheck):
    def run(self) -> CheckResult:
        db_path = get_db_path()
        details = []
        points = 20
        status = CheckStatus.PASS

        if not db_path.exists():
            details.append("⚠ Posture database missing (will auto-create on scan)")
            points -= 5
            status = CheckStatus.WARNING
        else:
            try:
                with sqlite3.connect(db_path) as conn:
                    cursor = conn.cursor()
                    cursor.execute("SELECT count(*) FROM scan_runs")
                    count = cursor.fetchone()[0]
                    details.append(f"✓ Posture history database operational ({count} scan runs recorded)")
            except sqlite3.Error as e:
                details.append(f"✖ Posture database error: {e}")
                points -= 20
                status = CheckStatus.FAIL

        return CheckResult(
            name="Database Check",
            category="Database",
            status=status,
            score_points=max(0, points),
            message="Database health validated",
            details=details
        )


class LoggingCheck(DoctorCheck):
    def run(self) -> CheckResult:
        config_dir = get_config_dir()
        logs_dir = config_dir / "logs"
        details = []
        points = 20
        status = CheckStatus.PASS

        try:
            logs_dir.mkdir(parents=True, exist_ok=True)
            log_file = logs_dir / "pulse.log"
            test_file = logs_dir / ".log_perm_check.tmp"
            with open(test_file, "w") as f:
                f.write("test")
            test_file.unlink()
            details.append(f"✓ Log directory writable: {logs_dir}")
            if log_file.exists():
                details.append(f"✓ Active log file present: {log_file} ({log_file.stat().st_size} bytes)")
            else:
                details.append(f"✓ Log file ready: {log_file}")
        except Exception as e:
            details.append(f"✖ Logging directory error: {e}")
            points -= 20
            status = CheckStatus.FAIL

        return CheckResult(
            name="Logging Check",
            category="Logging",
            status=status,
            score_points=max(0, points),
            message="Logging subsystem operational",
            details=details
        )


class NetworkingCheck(DoctorCheck):
    def run(self) -> CheckResult:
        offline = get_setting("OFFLINE_MODE", "false").lower() in ("true", "1", "yes")
        details = []
        points = 20
        status = CheckStatus.PASS

        if offline:
            details.append("⚠ OFFLINE_MODE enabled in configuration")
            points -= 5
            status = CheckStatus.WARNING

        try:
            with httpx.Client(timeout=5.0) as client:
                res = client.get("https://api.osv.dev/v1/query")
                if res.status_code < 500:
                    details.append("✓ Remote network connectivity verified (api.osv.dev reachable)")
                else:
                    details.append(f"⚠ Remote network endpoint status: HTTP {res.status_code}")
                    points -= 8
                    status = CheckStatus.WARNING
        except Exception as e:
            if offline:
                details.append(f"○ Offline mode active (Network check skipped: {e})")
            else:
                details.append(f"✖ Network connectivity check failed: {e}")
                points -= 12
                status = CheckStatus.WARNING

        return CheckResult(
            name="Networking Check",
            category="Networking",
            status=status,
            score_points=max(0, points),
            message="Connectivity verified" if status == CheckStatus.PASS else "Connectivity issues detected",
            details=details
        )


class ProviderCheck(DoctorCheck):
    def run(self) -> CheckResult:
        nvd_key = get_setting("NVD_API_KEY")
        details = []
        points = 20
        status = CheckStatus.PASS

        if nvd_key:
            masked = nvd_key[:4] + "..." + nvd_key[-4:] if len(nvd_key) > 8 else "[SET]"
            details.append(f"✓ NVD API Key configured: {masked} (High rate-limits enabled)")
        else:
            details.append("⚠ NVD API Key unset (Low rate-limit tier: 6s delays active)")
            points -= 4
            status = CheckStatus.WARNING

        details.append("✓ OSV Provider endpoint configured")
        details.append("✓ FIRST EPSS Provider endpoint configured")
        details.append("✓ CISA KEV Provider endpoint configured")

        return CheckResult(
            name="Provider Check",
            category="Providers",
            status=status,
            score_points=max(0, points),
            message="Intelligence providers ready",
            details=details
        )


class WebsiteCheck(DoctorCheck):
    def run(self) -> CheckResult:
        timeout = get_setting("HTTP_TIMEOUT", "10")
        redirects = get_setting("MAX_REDIRECTS", "5")
        ext_only = get_setting("EXTERNAL_ONLY", "false")

        details = [
            f"✓ HTTP Timeout: {timeout}s",
            f"✓ Max Redirects: {redirects}",
            f"✓ External Only IP Filter: {ext_only}"
        ]

        return CheckResult(
            name="Website Check",
            category="Website Scanner",
            status=CheckStatus.PASS,
            score_points=20,
            message="Website scanner parameters valid",
            details=details
        )


class DoctorRunner:
    """Registry runner for executing modular diagnostic checks and computing System Health Score."""

    _checks: List[DoctorCheck] = []

    @classmethod
    def register(cls, check_instance: DoctorCheck) -> None:
        cls._checks.append(check_instance)

    @classmethod
    def initialize_default_checks(cls) -> None:
        cls._checks = [
            ConfigurationCheck(),
            FilesystemCheck(),
            DatabaseCheck(),
            LoggingCheck(),
            NetworkingCheck(),
            ProviderCheck(),
            WebsiteCheck()
        ]

    @classmethod
    def run_all(cls) -> Tuple[int, CheckStatus, List[CheckResult], Dict[str, Tuple[int, int]]]:
        if not cls._checks:
            cls.initialize_default_checks()

        results: List[CheckResult] = []
        cat_scores: Dict[str, Tuple[int, int]] = {}

        total_earned = 0
        total_max = 0

        for check in cls._checks:
            res = check.run()
            results.append(res)

            earned, max_p = cat_scores.get(res.category, (0, 0))
            cat_scores[res.category] = (earned + res.score_points, max_p + res.max_points)

            total_earned += res.score_points
            total_max += res.max_points

        score_pct = int(round((total_earned / total_max) * 100)) if total_max > 0 else 0

        if score_pct >= 85:
            overall_status = CheckStatus.PASS
        elif score_pct >= 70:
            overall_status = CheckStatus.WARNING
        else:
            overall_status = CheckStatus.FAIL

        return score_pct, overall_status, results, cat_scores

    @classmethod
    def export(cls, format: str = "json") -> str:
        score_pct, overall_status, results, cat_scores = cls.run_all()
        data = {
            "system_health_score": f"{score_pct}%",
            "overall_status": overall_status.value,
            "generated_at": datetime.now().isoformat(),
            "tool_version": f"PULSE {__version__}",
            "category_breakdown": {cat: f"{pts[0]}/{pts[1]}" for cat, pts in cat_scores.items()},
            "check_results": [
                {
                    "name": r.name,
                    "category": r.category,
                    "status": r.status.value,
                    "score": f"{r.score_points}/{r.max_points}",
                    "message": r.message,
                    "details": r.details
                }
                for r in results
            ]
        }

        if format.lower() == "json":
            return json.dumps(data, indent=2, ensure_ascii=False)
        elif format.lower() in ("md", "markdown"):
            lines = [
                f"# PULSE Doctor Diagnostic Report",
                f"**Overall System Health Score**: {score_pct}% ({overall_status.value})",
                f"**Tool Version**: PULSE {__version__}",
                "",
                "## Score Breakdown",
                "| Category | Points | Status |",
                "| --- | --- | --- |"
            ]
            for cat, pts in cat_scores.items():
                cat_stat = "PASS" if pts[0] == pts[1] else ("WARNING" if pts[0] >= pts[1] * 0.7 else "FAIL")
                lines.append(f"| {cat} | {pts[0]} / {pts[1]} | {cat_stat} |")
            lines.append("")
            lines.append("## Check Details")
            for r in results:
                lines.append(f"### {r.name} ({r.status.value})")
                lines.append(f"**Score**: {r.score_points}/{r.max_points}")
                for d in r.details:
                    lines.append(f"- {d}")
                lines.append("")
            return "\n".join(lines)

        return json.dumps(data, indent=2)
